spring:
  application.name: online-store-application
  profiles.active: development
  datasource:
    url: jdbc:postgresql://localhost/online_store
    username: postgres
    password: changeit
orders:
  service.url: http://orders.${spring.profiles.active}.example.com
  storage:
    path: /storage/ftp/orders
resilience4j.circuitbreaker:
  backends:
    ordersServiceClient:
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 5
      waitInterval: 5000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
resilience4j.retry:
  backends:
  - name: ordersFileWriter
    maxAttempts: 3
    intervalInMillis: 1000
---
spring:
  profiles: development
---
spring:
  profiles: staging
---
spring:
  profiles: production